### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by qkbock**
reformatted the person/profile page to reflect changes we discussed and added the jason decoy headshot

### CODE REVIEW

**Comment by mattfelsen** [comment]
What is jason decoy headshot?

**Comment by qkbock** [comment]
http://jsfiddle.net/xZ8WT/33/

**Comment by mattfelsen** [comment]
What's up with the images in the project detail sitting inside a container that scrolls?

**Comment by qkbock** [comment]
I thought we wanted that? Might have misinterpreted but I Thought our original idea was that website fei showed us (text sticks to the top and images scroll beside it (that one coolly had the text linked to images but I don't think we have functionality for that in the word press form and it seems like people might mess it up a lot)) but from what I saw there didn't seem be tons of text in anyone's discription yet so I just made the image section match the height of the text section and scroll the overflow. I put a padding at the bottom of the image section which is a bit too big right now so even if there is just a single image it still scrolls but that can be easily changed. I also didn't incorporate any of the collapsing (ie of the person section) yet because from what there is now it looked like it would collapse the page to be super short mostly highlighting the footer which isn't that fun. 

Q

**Pull request merged**
